# Workflow

# Workflow (No indentation require for naming the workflow)
name: Hello

#on tells when the workflow should run (Give indentation)
on:
  workflow_dispatch:
# Jobs
# Should be inside the workflow

#Job tells what the workflow should do, there can be one or more than one jobs, hence we write jobs
#Jobs is an object  so needs indentation

  Jobs:
#1st Job (give indentation)
   say-hello:

 #Creats an Ephermal container with ubuntu running
  runs on: ubuntu latest
  #that ephermal container will have steps to execute, hence name those steps
 
   steps:
  -name: Say hello to everyone
  run: echo "Hello Dosto"
# Steps

# Should be insite the job

# Actions

# Should be inside the Steps
